version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Compiling the Node.js code
      - echo Running unit tests
  post_build:
    commands:
      - echo Build completed 
artifacts:
  files:
    - '**/*'
